name = "SpineBasedRecordLinkage"
uuid = "c1ccfb80-616c-11e9-2032-47e8246e4458"
authors = ["Jock Lawrie <jock.lawrie@gmail.com>"]
version = "0.4.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Schemata = "b4d66a32-c6c0-5461-b6fa-34bb9cecaf85"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CSV = "0.8.3"
DataFrames = "0.22.5"
Schemata = "3.0.0"
StringDistances = "0.10.0"
Tables = "1.3.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
